type: object
additionalProperties: false
properties:
  keys:
    description: >
      This describes a collection of KMS keys and their aliases. See the description for an individual pool stack for more details.
    type: array
    items: {$ref: "#/definitions/key"}

  tags:
    description: >
      Optional tags attached to your keys to make it easier to track and monitor.
    type: object
