{{#if vpc}}
AWSTemplateFormatVersion: "2010-09-09"
Description: Panda Sky Mixin - KMS
Parameters:
  VPC:
    Type: String
  Subnets:
    Type: String
  AvailabilityZones:
    Type: String
  SecurityGroups:
    Type: String
  RouteTables:
    Type: String

Resources:

  EndpointKMS:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcId: !Ref VPC
      ServiceName: com.amazonaws.{{deployment.region}}.kms
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds: !Split [ ",", !Ref Subnets ]
      SecurityGroupIds: !Split [ ",", !Ref SecurityGroups ]
{{/if}}
